CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS documents (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  file_name UUID NOT NULL DEFAULT gen_random_uuid(),
  file_extension TEXT NOT NULL,
  meta_data JSONB NOT NULL,
  upload_at TIMESTAMPTZ NOT NULL DEFAULT now()
);